# Changes here will be overwritten by Copier
_commit: 0.0.24-9-g6618310
_src_path: .
author_email: edgarrm358@gmail.com
author_fullname: Edgar Ramírez-Mondragón
author_username: edgarrmondragon
dependabot_update_time: '10:00'
dependabot_update_timezone: UTC
python_main_version: '3.10'
repository_name: tap-crowd-dev
repository_namespace: edgarrmondragon
repository_provider: github.com
repository_visibility: private
tap_auth_method: Bearer Token
tap_id: tap-crowd-dev
tap_package_command_line_name: tap-crowd-dev
tap_package_distribution_name: tap-crowd-dev
tap_package_import_name: tap_crowd_dev
tap_source_description: Customer Data Platform for Open-Source startups
tap_source_id: CrowdDev
tap_source_name: Crowd Dev
tap_stream_type: REST
vscode_files: true
