name: Test tap-crowd-dev

on:
  push:
    branches: [main]
    paths:
      - tap_crowd_dev/**
      - tests/**
      - noxfile.py
      - poetry.lock
      - pyproject.toml
      - .github/workflows/test.yml
      - .github/workflows/constraints.txt
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - tap_crowd_dev/**
      - tests/**
      - noxfile.py
      - poetry.lock
      - pyproject.toml
      - .github/workflows/test.yml
      - .github/workflows/constraints.txt

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: "1"
      NOXSESSION: tests-${{ matrix.python-version }}
      PIP_CONSTRAINT: .github/workflows/constraints.txt
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Upgrade pip
      run: |
        pip install pip
        pip --version

    - name: Install Poetry
      run: |
        pipx install poetry
        poetry --version
        poetry self show plugins

    - name: Install Nox
      run: |
        pipx install nox
        pipx inject nox nox-poetry
        nox --version

    - name: Run tests
      env:
        TAP_CROWD_DEV_TENANT_ID: ${{ secrets.TAP_CROWD_DEV_TENANT_ID }}
        TAP_CROWD_DEV_TOKEN: ${{ secrets.TAP_CROWD_DEV_TOKEN }}
        TAP_CROWD_DEV_START_DATE: ${{ secrets.TAP_CROWD_DEV_START_DATE }}
      run: |
        nox
